name: nuromood_app
description: Nuromood Emotion Classifier Mobile App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.0
  image_picker: ^1.2.0
  http: ^1.0.0
  shared_preferences: ^2.2.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.6
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite_sqlcipher: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
